# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb-haml}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yehuda Katz"]
  s.date = %q{2010-03-20}
  s.description = %q{Merb plugin for HAML support}
  s.email = %q{ykatz@engineyard.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    "Generators",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "lib/generators/controller.rb",
     "lib/generators/layout.rb",
     "lib/generators/resource_controller.rb",
     "lib/generators/templates/controller/app/views/%file_name%/index.html.haml",
     "lib/generators/templates/layout/app/views/layout/%file_name%.html.haml",
     "lib/generators/templates/resource_controller/activerecord/app/views/%file_name%/edit.html.haml",
     "lib/generators/templates/resource_controller/activerecord/app/views/%file_name%/index.html.haml",
     "lib/generators/templates/resource_controller/activerecord/app/views/%file_name%/new.html.haml",
     "lib/generators/templates/resource_controller/activerecord/app/views/%file_name%/show.html.haml",
     "lib/generators/templates/resource_controller/datamapper/app/views/%file_name%/edit.html.haml",
     "lib/generators/templates/resource_controller/datamapper/app/views/%file_name%/index.html.haml",
     "lib/generators/templates/resource_controller/datamapper/app/views/%file_name%/new.html.haml",
     "lib/generators/templates/resource_controller/datamapper/app/views/%file_name%/show.html.haml",
     "lib/generators/templates/resource_controller/none/app/views/%file_name%/edit.html.haml",
     "lib/generators/templates/resource_controller/none/app/views/%file_name%/index.html.haml",
     "lib/generators/templates/resource_controller/none/app/views/%file_name%/new.html.haml",
     "lib/generators/templates/resource_controller/none/app/views/%file_name%/show.html.haml",
     "lib/generators/templates/resource_controller/sequel/app/views/%file_name%/edit.html.haml",
     "lib/generators/templates/resource_controller/sequel/app/views/%file_name%/index.html.haml",
     "lib/generators/templates/resource_controller/sequel/app/views/%file_name%/new.html.haml",
     "lib/generators/templates/resource_controller/sequel/app/views/%file_name%/show.html.haml",
     "lib/merb-haml.rb",
     "lib/merb-haml/merbtasks.rb",
     "lib/merb-haml/template.rb",
     "lib/merb-haml/version.rb",
     "spec/controllers/haml.rb",
     "spec/controllers/views/capture_haml/index.html.haml",
     "spec/controllers/views/concat_haml/index.html.haml",
     "spec/controllers/views/haml_config/index.html.haml",
     "spec/controllers/views/haml_controller/index.html.haml",
     "spec/controllers/views/partial_haml/_partial_haml.html.haml",
     "spec/controllers/views/partial_haml/index.html.haml",
     "spec/controllers/views/partial_ivars/_partial_haml.html.haml",
     "spec/controllers/views/partial_ivars/index.html.haml",
     "spec/haml_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://merbivore.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Merb plugin that provides support for writing view template with HAML}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<merb-core>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<haml>, [">= 2.0.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<merb-core>, ["~> 1.1.0"])
      s.add_dependency(%q<haml>, [">= 2.0.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<merb-core>, ["~> 1.1.0"])
    s.add_dependency(%q<haml>, [">= 2.0.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

