# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb}
  s.version = "1.1.0.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["The Merb Team"]
  s.date = %q{2009-11-20}
  s.description = %q{The Merb stack}
  s.email = %q{team@merbivore.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "lib/merb.rb"
  ]
  s.homepage = %q{http://merbivore.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8.6")
  s.requirements = ["install the json gem to get faster json parsing"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{The Merb stack includes the most common merb plugins plus datamapper}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<merb-core>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-action-args>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-assets>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-auth>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-cache>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-exceptions>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-gen>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-haml>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-helpers>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-mailer>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-param-protection>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb-slices>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<merb_datamapper>, ["= 1.1.0.pre"])
      s.add_runtime_dependency(%q<do_sqlite3>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-timestamps>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-types>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-aggregates>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-validations>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-sweatshop>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-serializer>, ["~> 0.10"])
      s.add_runtime_dependency(%q<dm-constraints>, ["~> 0.10"])
    else
      s.add_dependency(%q<merb-core>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-action-args>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-assets>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-auth>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-cache>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-exceptions>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-gen>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-haml>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-helpers>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-mailer>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-param-protection>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb-slices>, ["= 1.1.0.pre"])
      s.add_dependency(%q<merb_datamapper>, ["= 1.1.0.pre"])
      s.add_dependency(%q<do_sqlite3>, ["~> 0.10"])
      s.add_dependency(%q<dm-timestamps>, ["~> 0.10"])
      s.add_dependency(%q<dm-types>, ["~> 0.10"])
      s.add_dependency(%q<dm-aggregates>, ["~> 0.10"])
      s.add_dependency(%q<dm-validations>, ["~> 0.10"])
      s.add_dependency(%q<dm-sweatshop>, ["~> 0.10"])
      s.add_dependency(%q<dm-serializer>, ["~> 0.10"])
      s.add_dependency(%q<dm-constraints>, ["~> 0.10"])
    end
  else
    s.add_dependency(%q<merb-core>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-action-args>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-assets>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-auth>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-cache>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-exceptions>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-gen>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-haml>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-helpers>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-mailer>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-param-protection>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb-slices>, ["= 1.1.0.pre"])
    s.add_dependency(%q<merb_datamapper>, ["= 1.1.0.pre"])
    s.add_dependency(%q<do_sqlite3>, ["~> 0.10"])
    s.add_dependency(%q<dm-timestamps>, ["~> 0.10"])
    s.add_dependency(%q<dm-types>, ["~> 0.10"])
    s.add_dependency(%q<dm-aggregates>, ["~> 0.10"])
    s.add_dependency(%q<dm-validations>, ["~> 0.10"])
    s.add_dependency(%q<dm-sweatshop>, ["~> 0.10"])
    s.add_dependency(%q<dm-serializer>, ["~> 0.10"])
    s.add_dependency(%q<dm-constraints>, ["~> 0.10"])
  end
end

