### AUTOMATICALLY GENERATED. DO NOT EDIT!

require 'merb-core'
require 'merb-action-args'
require 'merb-assets'
require 'merb-auth'
require 'merb-cache'
require 'merb-exceptions'
require 'merb-gen'
require 'merb-haml'
require 'merb-helpers'
require 'merb-mailer'
require 'merb-param-protection'
require 'merb-slices'
require 'merb_datamapper'
require 'do_sqlite3'
require 'dm-timestamps'
require 'dm-types'
require 'dm-aggregates'
require 'dm-migrations'
require 'dm-validations'
require 'dm-sweatshop'
require 'dm-serializer'
